##### Copyright 2019 The TensorFlow Authors.


In [1]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Load CSV data

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://www.tensorflow.org/tutorials/load_data/csv"><img src="https://www.tensorflow.org/images/tf_logo_32px.png" />View on TensorFlow.org</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/load_data/csv.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/docs/blob/master/site/en/tutorials/load_data/csv.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
  <td>
    <a href="https://storage.googleapis.com/tensorflow_docs/docs/site/en/tutorials/load_data/csv.ipynb"><img src="https://www.tensorflow.org/images/download_logo_32px.png" />Download notebook</a>
  </td>
</table>

This tutorial provides an example of how to load CSV data from a file into a `tf.data.Dataset`.

The data used in this tutorial are taken from the Titanic passenger list. The model will predict the likelihood a passenger survived based on characteristics like age, gender, ticket class, and whether the person was traveling alone.

## Setup

In [2]:
import functools

import numpy as np
import tensorflow as tf

In [3]:
TRAIN_DATA_URL = "https://storage.googleapis.com/tf-datasets/titanic/train.csv"
TEST_DATA_URL = "https://storage.googleapis.com/tf-datasets/titanic/eval.csv"

train_file_path = tf.keras.utils.get_file("train.csv", TRAIN_DATA_URL)
test_file_path = tf.keras.utils.get_file("eval.csv", TEST_DATA_URL)

 8192/30874 [======>.......................] - ETA: 0s

32768/30874 [===============================] - 0s 0us/step


 8192/13049 [=================>............] - ETA: 0s

16384/13049 [=====================================] - 0s 0us/step


In [4]:
# Make numpy values easier to read.
np.set_printoptions(precision=3, suppress=True)

## Load data

To start, let's look at the top of the CSV file to see how it is formatted.

In [5]:
!head {train_file_path}

survived,sex,age,n_siblings_spouses,parch,fare,class,deck,embark_town,alone
0,male,22.0,1,0,7.25,Third,unknown,Southampton,n
1,female,38.0,1,0,71.2833,First,C,Cherbourg,n
1,female,26.0,0,0,7.925,Third,unknown,Southampton,y
1,female,35.0,1,0,53.1,First,C,Southampton,n
0,male,28.0,0,0,8.4583,Third,unknown,Queenstown,y
0,male,2.0,3,1,21.075,Third,unknown,Southampton,n
1,female,27.0,0,2,11.1333,Third,unknown,Southampton,n
1,female,14.0,1,0,30.0708,Second,unknown,Cherbourg,n
1,female,4.0,1,1,16.7,Third,G,Southampton,n


You can [load this using pandas](pandas_dataframe.ipynb), and pass the NumPy arrays to TensorFlow. If you need to scale up to a large set of files, or need a loader that integrates with [TensorFlow and tf.data](../../guide/data.ipynb) then use the `tf.data.experimental.make_csv_dataset` function:

The only column you need to identify explicitly is the one with the value that the model is intended to predict. 

In [6]:
LABEL_COLUMN = 'survived'
LABELS = [0, 1]

Now read the CSV data from the file and create a dataset. 

(For the full documentation, see `tf.data.experimental.make_csv_dataset`)


In [7]:
def get_dataset(file_path, **kwargs):
  dataset = tf.data.experimental.make_csv_dataset(
      file_path,
      batch_size=5, # Artificially small to make examples easier to show.
      label_name=LABEL_COLUMN,
      na_value="?",
      num_epochs=1,
      ignore_errors=True, 
      **kwargs)
  return dataset

raw_train_data = get_dataset(train_file_path)
raw_test_data = get_dataset(test_file_path)

In [8]:
def show_batch(dataset):
  for batch, label in dataset.take(1):
    for key, value in batch.items():
      print("{:20s}: {}".format(key,value.numpy()))

Each item in the dataset is a batch, represented as a tuple of (*many examples*, *many labels*). The data from the examples is organized in column-based tensors (rather than row-based tensors), each with as many elements as the batch size (5 in this case).

It might help to see this yourself.

In [9]:
show_batch(raw_train_data)

sex                 : [b'female' b'male' b'male' b'male' b'female']
age                 : [37. 26. 28. 19. 21.]
n_siblings_spouses  : [0 2 1 0 0]
parch               : [0 0 0 0 0]
fare                : [ 9.587  8.663 19.967  7.775 10.5  ]
class               : [b'Third' b'Third' b'Third' b'Third' b'Second']
deck                : [b'unknown' b'unknown' b'unknown' b'unknown' b'unknown']
embark_town         : [b'Southampton' b'Southampton' b'Southampton' b'Southampton'
 b'Southampton']
alone               : [b'y' b'n' b'n' b'y' b'y']


As you can see, the columns in the CSV are named. The dataset constructor will pick these names up automatically. If the file you are working with does not contain the column names in the first line, pass them in a list of strings to  the `column_names` argument in the `make_csv_dataset` function.

In [10]:
CSV_COLUMNS = ['survived', 'sex', 'age', 'n_siblings_spouses', 'parch', 'fare', 'class', 'deck', 'embark_town', 'alone']

temp_dataset = get_dataset(train_file_path, column_names=CSV_COLUMNS)

show_batch(temp_dataset)

sex                 : [b'male' b'male' b'female' b'male' b'male']
age                 : [20. 48. 28. 39. 30.]
n_siblings_spouses  : [0 0 0 0 0]
parch               : [0 0 0 0 0]
fare                : [ 7.854  7.854  7.75  24.15   7.225]
class               : [b'Third' b'Third' b'Third' b'Third' b'Third']
deck                : [b'unknown' b'unknown' b'unknown' b'unknown' b'unknown']
embark_town         : [b'Southampton' b'Southampton' b'Queenstown' b'Southampton' b'Cherbourg']
alone               : [b'y' b'y' b'y' b'y' b'y']


This example is going to use all the available columns. If you need to omit some columns from the dataset, create a list of just the columns you plan to use, and pass it into the (optional) `select_columns` argument of the constructor.


In [11]:
SELECT_COLUMNS = ['survived', 'age', 'n_siblings_spouses', 'class', 'deck', 'alone']

temp_dataset = get_dataset(train_file_path, select_columns=SELECT_COLUMNS)

show_batch(temp_dataset)

age                 : [60. 28. 41. 22. 25.]
n_siblings_spouses  : [1 1 0 0 1]
class               : [b'First' b'Third' b'Third' b'Third' b'First']
deck                : [b'D' b'unknown' b'unknown' b'unknown' b'B']
alone               : [b'n' b'n' b'n' b'y' b'n']


## Data preprocessing

A CSV file can contain a variety of data types. Typically you want to convert from those mixed types to a fixed length vector before feeding the data into your model.

TensorFlow has a built-in system for describing common input conversions: `tf.feature_column`, see [this tutorial](../keras/feature_columns) for details.


You can preprocess your data using any tool you like (like [nltk](https://www.nltk.org/) or [sklearn](https://scikit-learn.org/stable/)), and just pass the processed output to TensorFlow. 


The primary advantage of doing the preprocessing inside your model is that when you export the model it includes the preprocessing. This way you can pass the raw data directly to your model.

### Continuous data

If your data is already in an appropriate numeric format, you can pack the data into a vector before passing it off to the model:

In [12]:
SELECT_COLUMNS = ['survived', 'age', 'n_siblings_spouses', 'parch', 'fare']
DEFAULTS = [0, 0.0, 0.0, 0.0, 0.0]
temp_dataset = get_dataset(train_file_path, 
                           select_columns=SELECT_COLUMNS,
                           column_defaults = DEFAULTS)

show_batch(temp_dataset)

age                 : [19. 26. 22. 28. 41.]
n_siblings_spouses  : [0. 0. 0. 1. 0.]
parch               : [0. 0. 0. 1. 5.]
fare                : [10.171 10.5    9.35  15.246 39.688]


In [13]:
example_batch, labels_batch = next(iter(temp_dataset)) 

Here's a simple function that will pack together all the columns:

In [14]:
def pack(features, label):
  return tf.stack(list(features.values()), axis=-1), label

Apply this to each element of the dataset:

In [15]:
packed_dataset = temp_dataset.map(pack)

for features, labels in packed_dataset.take(1):
  print(features.numpy())
  print()
  print(labels.numpy())

[[27.     0.     2.    11.133]
 [61.     0.     0.    32.321]
 [18.     1.     0.     6.496]
 [28.     0.     0.    13.   ]
 [38.     0.     0.    13.   ]]

[1 0 0 1 0]


If you have mixed datatypes you may want to separate out these simple-numeric fields. The `tf.feature_column` api can handle them, but this incurs some overhead and should be avoided unless really necessary. Switch back to the mixed dataset:

In [16]:
show_batch(raw_train_data)

sex                 : [b'female' b'male' b'male' b'female' b'male']
age                 : [25. 42. 45. 28. 71.]
n_siblings_spouses  : [1 1 1 0 0]
parch               : [1 0 0 2 0]
fare                : [30.    52.    83.475  7.75  49.504]
class               : [b'Second' b'First' b'First' b'Third' b'First']
deck                : [b'unknown' b'unknown' b'C' b'unknown' b'unknown']
embark_town         : [b'Southampton' b'Southampton' b'Southampton' b'Queenstown' b'Cherbourg']
alone               : [b'n' b'n' b'n' b'n' b'y']


In [17]:
example_batch, labels_batch = next(iter(temp_dataset)) 

So define a more general preprocessor that selects a list of numeric features and packs them into a single column:

In [18]:
class PackNumericFeatures(object):
  def __init__(self, names):
    self.names = names

  def __call__(self, features, labels):
    numeric_features = [features.pop(name) for name in self.names]
    numeric_features = [tf.cast(feat, tf.float32) for feat in numeric_features]
    numeric_features = tf.stack(numeric_features, axis=-1)
    features['numeric'] = numeric_features

    return features, labels

In [19]:
NUMERIC_FEATURES = ['age','n_siblings_spouses','parch', 'fare']

packed_train_data = raw_train_data.map(
    PackNumericFeatures(NUMERIC_FEATURES))

packed_test_data = raw_test_data.map(
    PackNumericFeatures(NUMERIC_FEATURES))

In [20]:
show_batch(packed_train_data)

sex                 : [b'male' b'male' b'male' b'male' b'male']
class               : [b'Second' b'Third' b'Second' b'Third' b'Third']
deck                : [b'unknown' b'unknown' b'unknown' b'unknown' b'unknown']
embark_town         : [b'Southampton' b'Southampton' b'Southampton' b'Cherbourg' b'Southampton']
alone               : [b'y' b'y' b'y' b'y' b'y']
numeric             : [[36.     0.     0.    13.   ]
 [28.     0.     0.     7.796]
 [33.     0.     0.    12.275]
 [29.     0.     0.     7.896]
 [28.     0.     0.     7.896]]


In [21]:
example_batch, labels_batch = next(iter(packed_train_data)) 

#### Data Normalization

Continuous data should always be normalized.

In [22]:
import pandas as pd
desc = pd.read_csv(train_file_path)[NUMERIC_FEATURES].describe()
desc

age  n_siblings_spouses       parch        fare
count  627.000000          627.000000  627.000000  627.000000
mean    29.631308            0.545455    0.379585   34.385399
std     12.511818            1.151090    0.792999   54.597730
min      0.750000            0.000000    0.000000    0.000000
25%     23.000000            0.000000    0.000000    7.895800
50%     28.000000            0.000000    0.000000   15.045800
75%     35.000000            1.000000    0.000000   31.387500
max     80.000000            8.000000    5.000000  512.329200

In [23]:
MEAN = np.array(desc.T['mean'])
STD = np.array(desc.T['std'])

In [24]:
def normalize_numeric_data(data, mean, std):
  # Center the data
  return (data-mean)/std


Now create a numeric column. The `tf.feature_columns.numeric_column` API accepts a `normalizer_fn` argument, which will be run on each batch.

Bind the `MEAN` and `STD` to the normalizer fn using [`functools.partial`](https://docs.python.org/3/library/functools.html#functools.partial).

In [25]:
# See what you just created.
normalizer = functools.partial(normalize_numeric_data, mean=MEAN, std=STD)

numeric_column = tf.feature_column.numeric_column('numeric', normalizer_fn=normalizer, shape=[len(NUMERIC_FEATURES)])
numeric_columns = [numeric_column]
numeric_column

NumericColumn(key='numeric', shape=(4,), default_value=None, dtype=tf.float32, normalizer_fn=functools.partial(<function normalize_numeric_data at 0x7fcba56362f0>, mean=array([29.631,  0.545,  0.38 , 34.385]), std=array([12.512,  1.151,  0.793, 54.598])))

When you train the model, include this feature column to select and center this block of numeric data:

In [26]:
example_batch['numeric']

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[49.   ,  1.   ,  0.   , 76.729],
       [19.   ,  0.   ,  0.   , 10.171],
       [18.   ,  0.   ,  1.   , 23.   ],
       [22.   ,  0.   ,  0.   ,  9.35 ],
       [32.   ,  0.   ,  0.   , 30.5  ]], dtype=float32)>

In [27]:
numeric_layer = tf.keras.layers.DenseFeatures(numeric_columns)
numeric_layer(example_batch).numpy()

array([[ 1.548,  0.395, -0.479,  0.776],
       [-0.85 , -0.474, -0.479, -0.444],
       [-0.93 , -0.474,  0.782, -0.209],
       [-0.61 , -0.474, -0.479, -0.459],
       [ 0.189, -0.474, -0.479, -0.071]], dtype=float32)

The mean based normalization used here requires knowing the means of each column ahead of time.

### Categorical data

Some of the columns in the CSV data are categorical columns. That is, the content should be one of a limited set of options.

Use the `tf.feature_column` API to create a collection with a `tf.feature_column.indicator_column` for each categorical column.


In [28]:
CATEGORIES = {
    'sex': ['male', 'female'],
    'class' : ['First', 'Second', 'Third'],
    'deck' : ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
    'embark_town' : ['Cherbourg', 'Southhampton', 'Queenstown'],
    'alone' : ['y', 'n']
}


In [29]:
categorical_columns = []
for feature, vocab in CATEGORIES.items():
  cat_col = tf.feature_column.categorical_column_with_vocabulary_list(
        key=feature, vocabulary_list=vocab)
  categorical_columns.append(tf.feature_column.indicator_column(cat_col))

In [30]:
# See what you just created.
categorical_columns

[IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='sex', vocabulary_list=('male', 'female'), dtype=tf.string, default_value=-1, num_oov_buckets=0)),
 IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='class', vocabulary_list=('First', 'Second', 'Third'), dtype=tf.string, default_value=-1, num_oov_buckets=0)),
 IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='deck', vocabulary_list=('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'), dtype=tf.string, default_value=-1, num_oov_buckets=0)),
 IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='embark_town', vocabulary_list=('Cherbourg', 'Southhampton', 'Queenstown'), dtype=tf.string, default_value=-1, num_oov_buckets=0)),
 IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='alone', vocabulary_list=('y', 'n'), dtype=tf.string, default_value=-1, num_oov_buckets=0))]

In [31]:
categorical_layer = tf.keras.layers.DenseFeatures(categorical_columns)
print(categorical_layer(example_batch).numpy()[0])

[0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1.]


This will be become part of a data processing input later when you build the model.

### Combined preprocessing layer

Add the two feature column collections and pass them to a `tf.keras.layers.DenseFeatures` to create an input layer that will extract and preprocess both input types:

In [32]:
preprocessing_layer = tf.keras.layers.DenseFeatures(categorical_columns+numeric_columns)

In [33]:
print(preprocessing_layer(example_batch).numpy()[0])

[ 0.     1.     1.     0.     0.     0.     0.     0.     1.     0.
  0.     0.     0.     0.     0.     1.     0.     0.     1.548  0.395
 -0.479  0.776  0.     1.   ]


## Build the model

Build a `tf.keras.Sequential`, starting with the `preprocessing_layer`.

In [34]:
model = tf.keras.Sequential([
  preprocessing_layer,
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(1),
])

model.compile(
    loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
    optimizer='adam',
    metrics=['accuracy'])

## Train, evaluate, and predict

Now the model can be instantiated and trained.

In [35]:
train_data = packed_train_data.shuffle(500)
test_data = packed_test_data

In [36]:
model.fit(train_data, epochs=20)

Epoch 1/20


      1/Unknown - 0s 18us/step - loss: 0.6589 - accuracy: 0.8000

     16/Unknown - 0s 3ms/step - loss: 0.6214 - accuracy: 0.6250 

     31/Unknown - 0s 3ms/step - loss: 0.5917 - accuracy: 0.6516

     47/Unknown - 0s 3ms/step - loss: 0.5630 - accuracy: 0.6766

     63/Unknown - 0s 3ms/step - loss: 0.5453 - accuracy: 0.6857

     78/Unknown - 0s 3ms/step - loss: 0.5259 - accuracy: 0.7103

     94/Unknown - 0s 3ms/step - loss: 0.5129 - accuracy: 0.7340

    108/Unknown - 0s 3ms/step - loss: 0.5066 - accuracy: 0.7389

    123/Unknown - 0s 3ms/step - loss: 0.4977 - accuracy: 0.7484

126/126 [==============================] - 0s 3ms/step - loss: 0.4921 - accuracy: 0.7528


Epoch 2/20


  1/126 [..............................] - ETA: 0s - loss: 0.1727 - accuracy: 1.0000

 16/126 [==>...........................] - ETA: 0s - loss: 0.4329 - accuracy: 0.7875

 31/126 [======>.......................] - ETA: 0s - loss: 0.4029 - accuracy: 0.8258

 46/126 [=========>....................] - ETA: 0s - loss: 0.4352 - accuracy: 0.7913

 61/126 [=============>................] - ETA: 0s - loss: 0.4484 - accuracy: 0.7869

 75/126 [================>.............] - ETA: 0s - loss: 0.4409 - accuracy: 0.7947

 90/126 [====================>.........] - ETA: 0s - loss: 0.4462 - accuracy: 0.7933

106/126 [========================>.....] - ETA: 0s - loss: 0.4479 - accuracy: 0.7962

122/126 [============================>.] - ETA: 0s - loss: 0.4341 - accuracy: 0.8056

126/126 [==============================] - 0s 3ms/step - loss: 0.4259 - accuracy: 0.8102


Epoch 3/20


  1/126 [..............................] - ETA: 0s - loss: 0.3056 - accuracy: 1.0000

 16/126 [==>...........................] - ETA: 0s - loss: 0.5070 - accuracy: 0.8052

 32/126 [======>.......................] - ETA: 0s - loss: 0.4183 - accuracy: 0.8408

 47/126 [==========>...................] - ETA: 0s - loss: 0.4260 - accuracy: 0.8319

 62/126 [=============>................] - ETA: 0s - loss: 0.4132 - accuracy: 0.8306

 78/126 [=================>............] - ETA: 0s - loss: 0.4076 - accuracy: 0.8372

 94/126 [=====================>........] - ETA: 0s - loss: 0.4169 - accuracy: 0.8287

109/126 [========================>.....] - ETA: 0s - loss: 0.4146 - accuracy: 0.8247

124/126 [============================>.] - ETA: 0s - loss: 0.4053 - accuracy: 0.8314

126/126 [==============================] - 0s 3ms/step - loss: 0.4011 - accuracy: 0.8341


Epoch 4/20
  1/126 [..............................] - ETA: 0s - loss: 0.0781 - accuracy: 1.0000

 16/126 [==>...........................] - ETA: 0s - loss: 0.2310 - accuracy: 0.8875

 31/126 [======>.......................] - ETA: 0s - loss: 0.3334 - accuracy: 0.8387

 46/126 [=========>....................] - ETA: 0s - loss: 0.3521 - accuracy: 0.8391

 62/126 [=============>................] - ETA: 0s - loss: 0.3662 - accuracy: 0.8355

 78/126 [=================>............] - ETA: 0s - loss: 0.3663 - accuracy: 0.8398

 94/126 [=====================>........] - ETA: 0s - loss: 0.3846 - accuracy: 0.8266

110/126 [=========================>....] - ETA: 0s - loss: 0.3804 - accuracy: 0.8318

126/126 [==============================] - ETA: 0s - loss: 0.3965 - accuracy: 0.8262

126/126 [==============================] - 0s 3ms/step - loss: 0.3965 - accuracy: 0.8262


Epoch 5/20
  1/126 [..............................] - ETA: 0s - loss: 0.4951 - accuracy: 0.6000

 17/126 [===>..........................] - ETA: 0s - loss: 0.3869 - accuracy: 0.8000

 33/126 [======>.......................] - ETA: 0s - loss: 0.3872 - accuracy: 0.8121

 49/126 [==========>...................] - ETA: 0s - loss: 0.3862 - accuracy: 0.8082

 65/126 [==============>...............] - ETA: 0s - loss: 0.3882 - accuracy: 0.8137

 80/126 [==================>...........] - ETA: 0s - loss: 0.3908 - accuracy: 0.8161

 96/126 [=====================>........] - ETA: 0s - loss: 0.3896 - accuracy: 0.8239

111/126 [=========================>....] - ETA: 0s - loss: 0.3673 - accuracy: 0.8351

126/126 [==============================] - ETA: 0s - loss: 0.3704 - accuracy: 0.8389

126/126 [==============================] - 0s 3ms/step - loss: 0.3704 - accuracy: 0.8389


Epoch 6/20
  1/126 [..............................] - ETA: 0s - loss: 0.1286 - accuracy: 1.0000

 16/126 [==>...........................] - ETA: 0s - loss: 0.3527 - accuracy: 0.8625

 31/126 [======>.......................] - ETA: 0s - loss: 0.3951 - accuracy: 0.8289

 47/126 [==========>...................] - ETA: 0s - loss: 0.3690 - accuracy: 0.8578

 62/126 [=============>................] - ETA: 0s - loss: 0.3667 - accuracy: 0.8534

 78/126 [=================>............] - ETA: 0s - loss: 0.3741 - accuracy: 0.8475

 94/126 [=====================>........] - ETA: 0s - loss: 0.3586 - accuracy: 0.8587

110/126 [=========================>....] - ETA: 0s - loss: 0.3741 - accuracy: 0.8483

126/126 [==============================] - ETA: 0s - loss: 0.3736 - accuracy: 0.8453

126/126 [==============================] - 0s 3ms/step - loss: 0.3736 - accuracy: 0.8453


Epoch 7/20
  1/126 [..............................] - ETA: 0s - loss: 0.2690 - accuracy: 0.8000

 16/126 [==>...........................] - ETA: 0s - loss: 0.4464 - accuracy: 0.7625

 31/126 [======>.......................] - ETA: 0s - loss: 0.3687 - accuracy: 0.8158

 46/126 [=========>....................] - ETA: 0s - loss: 0.3536 - accuracy: 0.8370

 62/126 [=============>................] - ETA: 0s - loss: 0.3894 - accuracy: 0.8274

 77/126 [=================>............] - ETA: 0s - loss: 0.3823 - accuracy: 0.8298

 92/126 [====================>.........] - ETA: 0s - loss: 0.3637 - accuracy: 0.8446

107/126 [========================>.....] - ETA: 0s - loss: 0.3615 - accuracy: 0.8440

122/126 [============================>.] - ETA: 0s - loss: 0.3546 - accuracy: 0.8484

126/126 [==============================] - 0s 3ms/step - loss: 0.3637 - accuracy: 0.8469


Epoch 8/20


  1/126 [..............................] - ETA: 0s - loss: 0.5320 - accuracy: 0.8000

 16/126 [==>...........................] - ETA: 0s - loss: 0.3148 - accuracy: 0.8875

 32/126 [======>.......................] - ETA: 0s - loss: 0.3125 - accuracy: 0.8813

 48/126 [==========>...................] - ETA: 0s - loss: 0.3285 - accuracy: 0.8667

 64/126 [==============>...............] - ETA: 0s - loss: 0.3482 - accuracy: 0.8580

 79/126 [=================>............] - ETA: 0s - loss: 0.3430 - accuracy: 0.8571

 95/126 [=====================>........] - ETA: 0s - loss: 0.3607 - accuracy: 0.8432

111/126 [=========================>....] - ETA: 0s - loss: 0.3538 - accuracy: 0.8442

126/126 [==============================] - 0s 3ms/step - loss: 0.3523 - accuracy: 0.8453


Epoch 9/20
  1/126 [..............................] - ETA: 0s - loss: 0.2154 - accuracy: 1.0000

 16/126 [==>...........................] - ETA: 0s - loss: 0.4057 - accuracy: 0.8250

 32/126 [======>.......................] - ETA: 0s - loss: 0.3153 - accuracy: 0.8813

 47/126 [==========>...................] - ETA: 0s - loss: 0.3134 - accuracy: 0.8723

 62/126 [=============>................] - ETA: 0s - loss: 0.3271 - accuracy: 0.8742

 77/126 [=================>............] - ETA: 0s - loss: 0.3356 - accuracy: 0.8649

 93/126 [=====================>........] - ETA: 0s - loss: 0.3419 - accuracy: 0.8615

109/126 [========================>.....] - ETA: 0s - loss: 0.3466 - accuracy: 0.8579

125/126 [============================>.] - ETA: 0s - loss: 0.3495 - accuracy: 0.8553

126/126 [==============================] - 0s 3ms/step - loss: 0.3486 - accuracy: 0.8549


Epoch 10/20


  1/126 [..............................] - ETA: 0s - loss: 0.3951 - accuracy: 0.6000

 16/126 [==>...........................] - ETA: 0s - loss: 0.3319 - accuracy: 0.8182

 31/126 [======>.......................] - ETA: 0s - loss: 0.3323 - accuracy: 0.8487

 46/126 [=========>....................] - ETA: 0s - loss: 0.3098 - accuracy: 0.8634

 62/126 [=============>................] - ETA: 0s - loss: 0.3103 - accuracy: 0.8632

 77/126 [=================>............] - ETA: 0s - loss: 0.3100 - accuracy: 0.8639

 92/126 [====================>.........] - ETA: 0s - loss: 0.3183 - accuracy: 0.8600

107/126 [========================>.....] - ETA: 0s - loss: 0.3252 - accuracy: 0.8515

123/126 [============================>.] - ETA: 0s - loss: 0.3343 - accuracy: 0.8464

126/126 [==============================] - 0s 3ms/step - loss: 0.3407 - accuracy: 0.8437


Epoch 11/20


  1/126 [..............................] - ETA: 0s - loss: 0.6241 - accuracy: 0.8000

 16/126 [==>...........................] - ETA: 0s - loss: 0.3109 - accuracy: 0.8750

 32/126 [======>.......................] - ETA: 0s - loss: 0.3011 - accuracy: 0.8813

 47/126 [==========>...................] - ETA: 0s - loss: 0.3190 - accuracy: 0.8638

 63/126 [==============>...............] - ETA: 0s - loss: 0.3253 - accuracy: 0.8508

 79/126 [=================>............] - ETA: 0s - loss: 0.3317 - accuracy: 0.8506

 95/126 [=====================>........] - ETA: 0s - loss: 0.3275 - accuracy: 0.8496

110/126 [=========================>....] - ETA: 0s - loss: 0.3274 - accuracy: 0.8574

126/126 [==============================] - ETA: 0s - loss: 0.3421 - accuracy: 0.8485

126/126 [==============================] - 0s 3ms/step - loss: 0.3421 - accuracy: 0.8485


Epoch 12/20
  1/126 [..............................] - ETA: 0s - loss: 0.6215 - accuracy: 0.8000

 16/126 [==>...........................] - ETA: 0s - loss: 0.3794 - accuracy: 0.8375

 32/126 [======>.......................] - ETA: 0s - loss: 0.3530 - accuracy: 0.8535

 48/126 [==========>...................] - ETA: 0s - loss: 0.3429 - accuracy: 0.8608

 64/126 [==============>...............] - ETA: 0s - loss: 0.3256 - accuracy: 0.8644

 80/126 [==================>...........] - ETA: 0s - loss: 0.3146 - accuracy: 0.8715

 96/126 [=====================>........] - ETA: 0s - loss: 0.3277 - accuracy: 0.8595

111/126 [=========================>....] - ETA: 0s - loss: 0.3433 - accuracy: 0.8533

126/126 [==============================] - ETA: 0s - loss: 0.3339 - accuracy: 0.8565

126/126 [==============================] - 0s 3ms/step - loss: 0.3339 - accuracy: 0.8565


Epoch 13/20
  1/126 [..............................] - ETA: 0s - loss: 0.1548 - accuracy: 0.8000

 16/126 [==>...........................] - ETA: 0s - loss: 0.2537 - accuracy: 0.9000

 31/126 [======>.......................] - ETA: 0s - loss: 0.2732 - accuracy: 0.8903

 46/126 [=========>....................] - ETA: 0s - loss: 0.2680 - accuracy: 0.8870

 61/126 [=============>................] - ETA: 0s - loss: 0.2955 - accuracy: 0.8721

 76/126 [=================>............] - ETA: 0s - loss: 0.3062 - accuracy: 0.8684

 91/126 [====================>.........] - ETA: 0s - loss: 0.3136 - accuracy: 0.8628

106/126 [========================>.....] - ETA: 0s - loss: 0.3235 - accuracy: 0.8596

122/126 [============================>.] - ETA: 0s - loss: 0.3174 - accuracy: 0.8600

126/126 [==============================] - 0s 3ms/step - loss: 0.3217 - accuracy: 0.8565


Epoch 14/20


  1/126 [..............................] - ETA: 0s - loss: 0.3785 - accuracy: 0.8000

 16/126 [==>...........................] - ETA: 0s - loss: 0.3238 - accuracy: 0.8625

 32/126 [======>.......................] - ETA: 0s - loss: 0.3615 - accuracy: 0.8438

 48/126 [==========>...................] - ETA: 0s - loss: 0.3202 - accuracy: 0.8583

 63/126 [==============>...............] - ETA: 0s - loss: 0.3062 - accuracy: 0.8603

 78/126 [=================>............] - ETA: 0s - loss: 0.3174 - accuracy: 0.8538

 93/126 [=====================>........] - ETA: 0s - loss: 0.3147 - accuracy: 0.8624

109/126 [========================>.....] - ETA: 0s - loss: 0.3205 - accuracy: 0.8542

125/126 [============================>.] - ETA: 0s - loss: 0.3206 - accuracy: 0.8505

126/126 [==============================] - 0s 3ms/step - loss: 0.3185 - accuracy: 0.8517


Epoch 15/20
  1/126 [..............................] - ETA: 0s - loss: 0.4385 - accuracy: 0.8000

 17/126 [===>..........................] - ETA: 0s - loss: 0.2682 - accuracy: 0.8941

 33/126 [======>.......................] - ETA: 0s - loss: 0.2414 - accuracy: 0.8909

 49/126 [==========>...................] - ETA: 0s - loss: 0.2724 - accuracy: 0.8776

 65/126 [==============>...............] - ETA: 0s - loss: 0.2909 - accuracy: 0.8738

 81/126 [==================>...........] - ETA: 0s - loss: 0.3090 - accuracy: 0.8741

 97/126 [======================>.......] - ETA: 0s - loss: 0.3244 - accuracy: 0.8651

112/126 [=========================>....] - ETA: 0s - loss: 0.3216 - accuracy: 0.8671

126/126 [==============================] - 0s 3ms/step - loss: 0.3254 - accuracy: 0.8596


Epoch 16/20
  1/126 [..............................] - ETA: 0s - loss: 0.3319 - accuracy: 0.8000

 16/126 [==>...........................] - ETA: 0s - loss: 0.3158 - accuracy: 0.8875

 30/126 [======>.......................] - ETA: 0s - loss: 0.3344 - accuracy: 0.8707

 45/126 [=========>....................] - ETA: 0s - loss: 0.3544 - accuracy: 0.8378

 60/126 [=============>................] - ETA: 0s - loss: 0.3560 - accuracy: 0.8316

 75/126 [================>.............] - ETA: 0s - loss: 0.3302 - accuracy: 0.8495

 90/126 [====================>.........] - ETA: 0s - loss: 0.3095 - accuracy: 0.8591

105/126 [========================>.....] - ETA: 0s - loss: 0.2891 - accuracy: 0.8697

120/126 [===========================>..] - ETA: 0s - loss: 0.3087 - accuracy: 0.8593

126/126 [==============================] - 0s 3ms/step - loss: 0.3159 - accuracy: 0.8565


Epoch 17/20


  1/126 [..............................] - ETA: 0s - loss: 0.1121 - accuracy: 1.0000

 16/126 [==>...........................] - ETA: 0s - loss: 0.2818 - accuracy: 0.8375

 31/126 [======>.......................] - ETA: 0s - loss: 0.2569 - accuracy: 0.8968

 46/126 [=========>....................] - ETA: 0s - loss: 0.3080 - accuracy: 0.8696

 62/126 [=============>................] - ETA: 0s - loss: 0.3205 - accuracy: 0.8548

 77/126 [=================>............] - ETA: 0s - loss: 0.3259 - accuracy: 0.8494

 92/126 [====================>.........] - ETA: 0s - loss: 0.3254 - accuracy: 0.8522

107/126 [========================>.....] - ETA: 0s - loss: 0.3224 - accuracy: 0.8542

122/126 [============================>.] - ETA: 0s - loss: 0.3166 - accuracy: 0.8567

126/126 [==============================] - 0s 3ms/step - loss: 0.3118 - accuracy: 0.8596


Epoch 18/20


  1/126 [..............................] - ETA: 0s - loss: 0.2732 - accuracy: 0.8000

 16/126 [==>...........................] - ETA: 0s - loss: 0.2602 - accuracy: 0.8875

 32/126 [======>.......................] - ETA: 0s - loss: 0.2661 - accuracy: 0.8875

 47/126 [==========>...................] - ETA: 0s - loss: 0.2814 - accuracy: 0.8766

 62/126 [=============>................] - ETA: 0s - loss: 0.2869 - accuracy: 0.8762

 78/126 [=================>............] - ETA: 0s - loss: 0.2884 - accuracy: 0.8760

 93/126 [=====================>........] - ETA: 0s - loss: 0.3034 - accuracy: 0.8723

109/126 [========================>.....] - ETA: 0s - loss: 0.3067 - accuracy: 0.8690

124/126 [============================>.] - ETA: 0s - loss: 0.3097 - accuracy: 0.8639

126/126 [==============================] - 0s 3ms/step - loss: 0.3074 - accuracy: 0.8660


Epoch 19/20
  1/126 [..............................] - ETA: 0s - loss: 0.1155 - accuracy: 1.0000

 16/126 [==>...........................] - ETA: 0s - loss: 0.2696 - accuracy: 0.8625

 25/126 [====>.........................] - ETA: 0s - loss: 0.2353 - accuracy: 0.9040

 32/126 [======>.......................] - ETA: 0s - loss: 0.2428 - accuracy: 0.9000

 39/126 [========>.....................] - ETA: 0s - loss: 0.2728 - accuracy: 0.8923

 47/126 [==========>...................] - ETA: 0s - loss: 0.2955 - accuracy: 0.8894

 54/126 [===========>..................] - ETA: 0s - loss: 0.3073 - accuracy: 0.8815

 61/126 [=============>................] - ETA: 0s - loss: 0.3058 - accuracy: 0.8775

 68/126 [===============>..............] - ETA: 0s - loss: 0.2995 - accuracy: 0.8783

 75/126 [================>.............] - ETA: 0s - loss: 0.2944 - accuracy: 0.8763

 82/126 [==================>...........] - ETA: 0s - loss: 0.2969 - accuracy: 0.8722

 89/126 [====================>.........] - ETA: 0s - loss: 0.2937 - accuracy: 0.8733

 99/126 [======================>.......] - ETA: 0s - loss: 0.2913 - accuracy: 0.8720

113/126 [=========================>....] - ETA: 0s - loss: 0.2831 - accuracy: 0.8772

126/126 [==============================] - 1s 6ms/step - loss: 0.3012 - accuracy: 0.8660


Epoch 20/20
  1/126 [..............................] - ETA: 0s - loss: 0.5114 - accuracy: 0.8000

 14/126 [==>...........................] - ETA: 0s - loss: 0.2723 - accuracy: 0.9000

 28/126 [=====>........................] - ETA: 0s - loss: 0.2791 - accuracy: 0.9000

 42/126 [=========>....................] - ETA: 0s - loss: 0.2882 - accuracy: 0.8696

 57/126 [============>.................] - ETA: 0s - loss: 0.2969 - accuracy: 0.8546

 71/126 [===============>..............] - ETA: 0s - loss: 0.3031 - accuracy: 0.8551

 85/126 [===================>..........] - ETA: 0s - loss: 0.3153 - accuracy: 0.8555

100/126 [======================>.......] - ETA: 0s - loss: 0.2955 - accuracy: 0.8632

114/126 [==========================>...] - ETA: 0s - loss: 0.2870 - accuracy: 0.8677

126/126 [==============================] - 0s 4ms/step - loss: 0.3027 - accuracy: 0.8660


Once the model is trained, you can check its accuracy on the `test_data` set.

In [37]:
test_loss, test_accuracy = model.evaluate(test_data)

print('\n\nTest Loss {}, Test Accuracy {}'.format(test_loss, test_accuracy))

      1/Unknown - 0s 16us/step - loss: 0.3347 - accuracy: 1.0000

     19/Unknown - 0s 3ms/step - loss: 0.6063 - accuracy: 0.8105 

     37/Unknown - 0s 3ms/step - loss: 0.4845 - accuracy: 0.8324

53/53 [==============================] - 0s 3ms/step - loss: 0.4645 - accuracy: 0.8447




Test Loss 0.4644656777381897, Test Accuracy 0.8446969985961914


Use `tf.keras.Model.predict` to infer labels on a batch or a dataset of batches.

In [38]:
predictions = model.predict(test_data)

# Show some results
for prediction, survived in zip(predictions[:10], list(test_data)[0][1][:10]):
  prediction = tf.sigmoid(prediction).numpy()
  print("Predicted survival: {:.2%}".format(prediction[0]),
        " | Actual outcome: ",
        ("SURVIVED" if bool(survived) else "DIED"))


Predicted survival: 34.64%  | Actual outcome:  DIED
Predicted survival: 8.82%  | Actual outcome:  DIED
Predicted survival: 7.96%  | Actual outcome:  DIED
Predicted survival: 8.70%  | Actual outcome:  DIED
Predicted survival: 2.89%  | Actual outcome:  DIED
